### ISSUE TITLE
Exeption Caused by: sqlite4a.SQLiteException: no such table: users, while compiling: INSERT INTO users(_id, name) VALUES(?, ?);

### ISSUE THREAD

**Issue by progfiles** [DanielSerdyukov/rxsqlite#1]
Caused by: sqlite4a.SQLiteException: no such table: users, while compiling: INSERT INTO users(_id, name) VALUES(?, ?);

**Comment by DanielSerdyukov** [comment]
If you'r using ProGuard, try to add lines below to proguard config

```
-keep class sqlite4a.** { *; }
-keep class **$$Schema { *; }
```

**Comment by progfiles** [comment]
It seems my fail.

That solve my trouble:
`.doOnOpen { it.exec("CREATE TABLE IF NOT EXISTS`...

But what about data migration?

Thanks!

**Comment by DanielSerdyukov** [comment]
One moment! You don't need to create tables manually, they are created automatically by annotation processor. If you'r using kotlin you should add `kapt 'rxsqlite:compiler:3.2.0'` line in dependencies block.

Data migration is not easiest feature. When? When is done =)

**Comment by progfiles** [comment]
ok. got it. Now I try it in java. I can get all data from table. But when I use were it is return " no such column:" =) But it is in table =)
