### ISSUE TITLE
How to update table

### ISSUE THREAD

**Issue by 2yllll** [DanielSerdyukov/rxsqlite#3]
cant find this method

**Comment by DanielSerdyukov** [comment]
Hi! What does it mean 'update table'? If you want update some value in table, you should change model(s) and then call SQLite.save(All) for it. Save method returns Rx.Observable and you should subscribe on it to apply changes.

If you want 'ALTER TABLE', just add doOnUpgrade action to RxSQLiteClient.Builder

```
RxSQLite.register(RxSQLiteClient.builder(this, <db version>) // don't forget change database version
    ...
    .doOnUpgrade(new Action<SQLiteDb, Integer, Integer>() {
        @Override
        public void call(SQLiteDb db, Integer oldVersion, Integer newVersion) {
             db.exec("ALTER TABLE ...");
        }
    })
    .build());
```

**Comment by 2yllll** [comment]
ok! thx:)
